#SPRING
spring:
  profiles:
    active: dev

  # DATASOURCE
  datasource:
    url: 'jdbc:oracle:thin:@192.168.1.156:1521/xgsid.xg156.com'
    username: 'ESTAR'
    password: 'ESTAR'
    driver-class-name: 'oracle.jdbc.OracleDriver'

# LOGGING
logging:
  config: 'classpath:logback.xml'
  level:
        org.springframework.jdbc: debug